FROM postgres:12.12
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=pass
ENV POSTGRES_DB =web
EXPOSE 5432

#docker run --name mydb -itd -p 5432:5432 my_db
#docker network create network 
#docker network ls
#docker run --name mydba <container name> --network mynetwork <network name> -p 8081:80 -d my_dba <image name>
