FROM dpage/pgadmin4:latest
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
EXPOSE 80

#docker build -t my_dba .
#docker run --name mydba -p 8081:80 -d my_dba
#port mapping to connect to the docker containers from the outside
#internal containers cant use port mapping, but instead put them on the same network

#docker run -e PGADMIN_DEFAULT_EMAIL =... -> -e give environment variable, don't do this because it 
#~too long put it in the Dockerfile instead

#sync volume = -v





